{
 "title": "PMI: Control Panel",
 "tags": [
  "PMI",
  "Overview",
  "Mission Control"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "target_node",
    "label": "Target Node",
    "query": "label_values(node_cpu_seconds_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "RAM usage by processes",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (groupname, instance) (namedprocess_namegroup_memory_bytes{groupname=~\"nginx|trex|jmeter|python3\", memtype=\"resident\"})",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "CPU usage by processes",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (groupname, instance) (rate(namedprocess_namegroup_cpu_seconds_total{groupname=~\"nginx|trex|jmeter|python3\"}[1m])) * 100) / 48",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "🚦 SYSTEMD STATUS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "chrony.service",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "0": "n",
       "1": "o",
       "2": "d",
       "3": "e",
       "4": "_",
       "5": "s",
       "6": "y",
       "7": "s",
       "8": "t",
       "9": "e",
       "10": "m",
       "11": "d",
       "12": "_",
       "13": "u",
       "14": "n",
       "15": "i",
       "16": "t",
       "17": "_",
       "18": "s",
       "19": "t",
       "20": "a",
       "21": "t",
       "22": "e",
       "23": "{",
       "24": "n",
       "25": "a",
       "26": "m",
       "27": "e",
       "28": "=",
       "29": "\"",
       "30": "n",
       "31": "g",
       "32": "i",
       "33": "n",
       "34": "x",
       "35": ".",
       "36": "s",
       "37": "e",
       "38": "r",
       "39": "v",
       "40": "i",
       "41": "c",
       "42": "e",
       "43": "\"",
       "44": "}",
       "expr": "node_systemd_unit_state{instance=\"localhost:9100\", name=\"chrony.service\", state=\"active\"}",
       "trace": 1
      }
     ]
    },
    {
     "title": "node_exporter.service",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 3, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "0": "n",
       "1": "o",
       "2": "d",
       "3": "e",
       "4": "_",
       "5": "s",
       "6": "y",
       "7": "s",
       "8": "t",
       "9": "e",
       "10": "m",
       "11": "d",
       "12": "_",
       "13": "u",
       "14": "n",
       "15": "i",
       "16": "t",
       "17": "_",
       "18": "s",
       "19": "t",
       "20": "a",
       "21": "t",
       "22": "e",
       "23": "{",
       "24": "n",
       "25": "a",
       "26": "m",
       "27": "e",
       "28": "=",
       "29": "\"",
       "30": "n",
       "31": "g",
       "32": "i",
       "33": "n",
       "34": "x",
       "35": ".",
       "36": "s",
       "37": "e",
       "38": "r",
       "39": "v",
       "40": "i",
       "41": "c",
       "42": "e",
       "43": "\"",
       "44": "}",
       "expr": "node_systemd_unit_state{instance=\"localhost:9100\", name=\"node_exporter.service\", state=\"active\"}",
       "trace": 1
      }
     ]
    },
    {
     "title": "nginx.service",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 7, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "0": "n",
       "1": "o",
       "2": "d",
       "3": "e",
       "4": "_",
       "5": "s",
       "6": "y",
       "7": "s",
       "8": "t",
       "9": "e",
       "10": "m",
       "11": "d",
       "12": "_",
       "13": "u",
       "14": "n",
       "15": "i",
       "16": "t",
       "17": "_",
       "18": "s",
       "19": "t",
       "20": "a",
       "21": "t",
       "22": "e",
       "23": "{",
       "24": "n",
       "25": "a",
       "26": "m",
       "27": "e",
       "28": "=",
       "29": "\"",
       "30": "n",
       "31": "g",
       "32": "i",
       "33": "n",
       "34": "x",
       "35": ".",
       "36": "s",
       "37": "e",
       "38": "r",
       "39": "v",
       "40": "i",
       "41": "c",
       "42": "e",
       "43": "\"",
       "44": "}",
       "expr": "node_systemd_unit_state{instance=\"localhost:9100\", name=\"nginx.service\", state=\"active\"}",
       "trace": 1
      }
     ]
    },
    {
     "title": "nginx-expose.service",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 10, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "0": "n",
       "1": "o",
       "2": "d",
       "3": "e",
       "4": "_",
       "5": "s",
       "6": "y",
       "7": "s",
       "8": "t",
       "9": "e",
       "10": "m",
       "11": "d",
       "12": "_",
       "13": "u",
       "14": "n",
       "15": "i",
       "16": "t",
       "17": "_",
       "18": "s",
       "19": "t",
       "20": "a",
       "21": "t",
       "22": "e",
       "23": "{",
       "24": "n",
       "25": "a",
       "26": "m",
       "27": "e",
       "28": "=",
       "29": "\"",
       "30": "n",
       "31": "g",
       "32": "i",
       "33": "n",
       "34": "x",
       "35": ".",
       "36": "s",
       "37": "e",
       "38": "r",
       "39": "v",
       "40": "i",
       "41": "c",
       "42": "e",
       "43": "\"",
       "44": "}",
       "expr": "node_systemd_unit_state{instance=\"localhost:9100\", name=\"nginx-expose.service\", state=\"active\"}",
       "trace": 1
      }
     ]
    },
    {
     "title": "nginx-exporter.service",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 13, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "0": "n",
       "1": "o",
       "2": "d",
       "3": "e",
       "4": "_",
       "5": "s",
       "6": "y",
       "7": "s",
       "8": "t",
       "9": "e",
       "10": "m",
       "11": "d",
       "12": "_",
       "13": "u",
       "14": "n",
       "15": "i",
       "16": "t",
       "17": "_",
       "18": "s",
       "19": "t",
       "20": "a",
       "21": "t",
       "22": "e",
       "23": "{",
       "24": "n",
       "25": "a",
       "26": "m",
       "27": "e",
       "28": "=",
       "29": "\"",
       "30": "n",
       "31": "g",
       "32": "i",
       "33": "n",
       "34": "x",
       "35": ".",
       "36": "s",
       "37": "e",
       "38": "r",
       "39": "v",
       "40": "i",
       "41": "c",
       "42": "e",
       "43": "\"",
       "44": "}",
       "expr": "node_systemd_unit_state{instance=\"localhost:9100\", name=\"nginx-prometheus-exporter.service\", state=\"active\"}",
       "trace": 1
      }
     ]
    },
    {
     "title": "victoriametrics.service",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 17, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "0": "n",
       "1": "o",
       "2": "d",
       "3": "e",
       "4": "_",
       "5": "s",
       "6": "y",
       "7": "s",
       "8": "t",
       "9": "e",
       "10": "m",
       "11": "d",
       "12": "_",
       "13": "u",
       "14": "n",
       "15": "i",
       "16": "t",
       "17": "_",
       "18": "s",
       "19": "t",
       "20": "a",
       "21": "t",
       "22": "e",
       "23": "{",
       "24": "n",
       "25": "a",
       "26": "m",
       "27": "e",
       "28": "=",
       "29": "\"",
       "30": "n",
       "31": "g",
       "32": "i",
       "33": "n",
       "34": "x",
       "35": ".",
       "36": "s",
       "37": "e",
       "38": "r",
       "39": "v",
       "40": "i",
       "41": "c",
       "42": "e",
       "43": "\"",
       "44": "}",
       "expr": "node_systemd_unit_state{instance=\"localhost:9100\", name=\"victoriametrics.service\", state=\"active\"}",
       "trace": 1
      }
     ]
    },
    {
     "title": "trex-2.service",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "0": "n",
       "1": "o",
       "2": "d",
       "3": "e",
       "4": "_",
       "5": "s",
       "6": "y",
       "7": "s",
       "8": "t",
       "9": "e",
       "10": "m",
       "11": "d",
       "12": "_",
       "13": "u",
       "14": "n",
       "15": "i",
       "16": "t",
       "17": "_",
       "18": "s",
       "19": "t",
       "20": "a",
       "21": "t",
       "22": "e",
       "23": "{",
       "24": "n",
       "25": "a",
       "26": "m",
       "27": "e",
       "28": "=",
       "29": "\"",
       "30": "n",
       "31": "g",
       "32": "i",
       "33": "n",
       "34": "x",
       "35": ".",
       "36": "s",
       "37": "e",
       "38": "r",
       "39": "v",
       "40": "i",
       "41": "c",
       "42": "e",
       "43": "\"",
       "44": "}",
       "expr": "node_systemd_unit_state{instance=\"localhost:9100\", name=\"nginx.service\", state=\"active\"}",
       "trace": 1
      }
     ]
    }
   ]
  },
  { "title": "🚨 REAL-TIME STATUS (KPI)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "L7 Victim Processed (NGINX)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L7 Attack Rate (JMeter)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jmeter_count{transaction=\"all\", statut=\"all\"}) / 5",
     "legendFormat": "Attack Rate"
    }
   ]
  },
  {
   "title": "L4 Packet Storm (TRex)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(pmi_trex_tx_pps)", "legendFormat": "PPS" }
   ]
  },
  {
   "title": "Target CPU Load (Node)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$target_node\"}[1m])) * 100)",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "L7 Client Error Rate (JMeter)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(jmeter_countError) / sum(jmeter_count)) * 100",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "L4 TX Bandwidth (TRex)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Gbit/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "0": "p",
     "1": "m",
     "2": "i",
     "3": "_",
     "4": "t",
     "5": "r",
     "6": "e",
     "7": "x",
     "8": "_",
     "9": "t",
     "10": "x",
     "11": "_",
     "12": "b",
     "13": "p",
     "14": "s",
     "expr": "sum(pmi_trex_tx_bps) / 1e9",
     "trace": 1
    }
   ]
  },
  { "title": "🔥 ATTACK IMPACT ANALYSIS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "L7 Correlation: Sent vs Handled",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(jmeter_count{transaction=\"all\", statut=\"all\"}) / 5",
     "legendFormat": "Attack Sent (JMeter)"
    },
    {
     "expr": "sum(rate(nginx_http_requests_total[1m]))",
     "legendFormat": "Target Processed (NGINX)"
    }
   ]
  },
  {
   "title": "L4 Correlation: Packet Storm vs System Load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "targets": [
    { "expr": "sum(pmi_trex_tx_pps)", "legendFormat": "TRex PPS" },
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$target_node\"}[1m])) * 100)",
     "legendFormat": "Target CPU %"
    }
   ]
  }
 ]
}