{
 "title": "PMI: L3 Load (TRex STL)",
 "tags": [
  "L4_tests",
  "PMI",
  "TRex",
  "generator"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "run_id",
    "label": "Run ID",
    "query": "label_values(pmi_trex_tx_bps, run_id)"
   },
   {
    "name": "port",
    "query": "label_values(pmi_trex_tx_pps, port)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total TX Bandwidth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pmi_trex_tx_bps{run_id=~\"$run_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total TX PPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pmi_trex_tx_pps{run_id=~\"$run_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total RX Bandwidth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pmi_trex_rx_bps{run_id=~\"$run_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Est. Packet Loss (TX - RX)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pmi_trex_tx_pkts{run_id=~\"$run_id\"}) - sum(pmi_trex_rx_pkts{run_id=~\"$run_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bandwidth per Port",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "pmi_trex_tx_bps{run_id=~\"$run_id\"}",
     "legendFormat": "TX Port {{port}}"
    },
    {
     "expr": "pmi_trex_rx_bps{run_id=~\"$run_id\"}",
     "legendFormat": "RX Port {{port}}"
    }
   ]
  },
  {
   "title": "PPS per Port",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "pmi_trex_tx_pps{run_id=~\"$run_id\", port=~\"$port\"}",
     "legendFormat": "TX PPS Port {{port}}"
    },
    {
     "expr": "pmi_trex_rx_pps{run_id=~\"$run_id\", port=~\"$port\"}",
     "legendFormat": "RX PPS Port {{port}}"
    }
   ]
  }
 ]
}