{
 "title": "PMI: Victim Dashboard (Nginx)",
 "tags": [
  "nginx",
  "PMI",
  "victim"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(nginx_http_requests_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "NGINX",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(nginx_up{instance=~\"$instance\"})",
     "trace": 1
    }
   ]
  },
  {
   "title": "RPS - Requests Per Second (5s average)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total{instance=~\"$instance\"}[5s]))",
     "legendFormat": "RPS (requests/sec)"
    }
   ]
  },
  {
   "title": "Active Connection Peak",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(nginx_connections_active{instance=~\"$instance\"}[$__range])"
    }
   ]
  },
  {
   "title": "Idle Connection Peak",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(nginx_connections_waiting{instance=~\"$instance\"}[$__range])"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nginx_connections_active{instance=~\"$instance\"})",
     "legendFormat": "Active Connections"
    }
   ]
  },
  {
   "title": "New Connections Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_connections_accepted{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Connections/sec"
    }
   ]
  },
  {
   "title": "Total Requests (in selected time range)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(nginx_http_requests_total{instance=~\"$instance\"}[$__range]))",
     "legendFormat": "Total Requests in range"
    }
   ]
  },
  {
   "title": "Connections Reading",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nginx_connections_reading{instance=~\"$instance\"})",
     "legendFormat": "Reading Requests"
    }
   ]
  },
  {
   "title": "Connections Writing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nginx_connections_writing{instance=~\"$instance\"})",
     "legendFormat": "Writing Responses"
    }
   ]
  },
  {
   "title": "Waiting Connections (idle)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nginx_connections_waiting{instance=~\"$instance\"})",
     "legendFormat": "Idle Waiting Connections"
    }
   ]
  }
 ]
}